import Foundation
import Observation

/// The sidebar's model. All business logic — the repository list, worktree
/// discovery (gitoxide), terminal sessions, and SQLite persistence — lives in
/// the async Rust core (`RepoStoreCore`). This is a thin `@MainActor`
/// `@Observable` adapter: it `await`s the core's async methods (which run on
/// Rust's Tokio runtime, off the main thread) and republishes the results into
/// stored properties on the main actor so SwiftUI re-renders safely.
@MainActor
@Observable
final class RepoStore {
    private(set) var repos: [Repo] = []
    private var worktreesByRepo: [String: [Worktree]] = [:]
    private var sessionsByWorktree: [String: [Session]] = [:]

    @ObservationIgnored private let core: RepoStoreCore

    init() {
        core = RepoStoreCore(dbPath: Self.databasePath())
    }

    /// Run migrations and load the initial state. Call once when the UI appears.
    func start() async {
        await core.open()
        await reload()
    }

    // MARK: - Synchronous snapshot reads (used directly in SwiftUI bodies)

    func worktrees(for repo: Repo) -> [Worktree] { worktreesByRepo[repo.path] ?? [] }
    func sessions(for worktree: Worktree) -> [Session] { sessionsByWorktree[worktree.path] ?? [] }

    // MARK: - Async mutations (await the Rust core, then refresh snapshots)

    /// Ensure a worktree has at least one session; call when it's first shown so
    /// a stable session UUID exists for the zmx terminal.
    func ensureSession(for worktree: Worktree) async {
        sessionsByWorktree[worktree.path] = await core.ensureSession(worktreePath: worktree.path)
    }

    /// Open a new session on `worktree` and return it.
    @discardableResult
    func addSession(to worktree: Worktree) async -> Session? {
        let session = await core.addSession(worktreePath: worktree.path)
        sessionsByWorktree[worktree.path] = await core.sessions(worktreePath: worktree.path)
        return session
    }

    /// Close a session (the UI keeps at least one open per worktree).
    func closeSession(_ session: Session) async {
        let path = session.worktreePath
        await core.closeSession(sessionId: session.id)
        sessionsByWorktree[path] = await core.sessions(worktreePath: path)
    }

    /// Add the git repository containing `folder`. Returns a localized error
    /// message on failure, nil on success (or if already present).
    @discardableResult
    func add(folder: String) async -> String? {
        let outcome = await core.addFolder(folder: folder)
        await reload()
        switch outcome {
        case .notARepository: return String(localized: "Not a git repository.")
        case .added, .alreadyPresent: return nil
        }
    }

    func remove(_ repo: Repo) async {
        await core.remove(repoId: repo.id)
        await reload()
    }

    /// Reorder the repositories via drag and drop, persisting the new order.
    func moveRepos(from source: IndexSet, to destination: Int) async {
        var ordered = repos
        ordered.move(fromOffsets: source, toOffset: destination)
        await core.reorderRepositories(orderedIds: ordered.map(\.id))
        await reload()
    }

    /// Pull the full state from Rust into the observable snapshots.
    private func reload() async {
        let loaded = await core.repos()
        var worktrees: [String: [Worktree]] = [:]
        var sessions: [String: [Session]] = [:]
        for repo in loaded {
            let list = core.worktrees(repoPath: repo.path)  // sync cache read
            worktrees[repo.path] = list
            for worktree in list {
                sessions[worktree.path] = await core.sessions(worktreePath: worktree.path)
            }
        }
        repos = loaded
        worktreesByRepo = worktrees
        sessionsByWorktree = sessions
    }

    /// The SQLite database under Application Support (`sh.piyo/piyo.sqlite`).
    private static func databasePath() -> String {
        let fm = FileManager.default
        let base =
            fm.urls(for: .applicationSupportDirectory, in: .userDomainMask).first
            ?? URL(fileURLWithPath: NSTemporaryDirectory())
        let dir = base.appendingPathComponent("sh.piyo", isDirectory: true)
        try? fm.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir.appendingPathComponent("piyo.sqlite").path
    }
}

// `Repo`, `Session`, `Worktree` are generated by UniFFI (Equatable/Hashable).
// The sidebar/tab strip list them, so they also need `Identifiable`. `Repo` and
// `Session` carry a UUID `id` field already; a `Worktree`'s path is its id.
extension Repo: Identifiable {}
extension Session: Identifiable {}
extension Worktree: Identifiable { public var id: String { path } }
